### ISSUE TITLE
Option to disable validation

### ISSUE THREAD

**Issue by st-schneider** [adamvoss/vscode-yaml#21]
I have some Symfony config files that currently do not fit into valid yaml, meaning some properties start with % and no ' or " before that.
Is there a way to disable the validation for valid yaml but keep the highlighting.

**Comment by JPinkney** [comment]
Hi, we have this in our extension (https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml). Turning off/on validation is available through the "yaml.validate" setting!

**Comment by st-schneider** [comment]
@JPinkney wonderful, I'll use that then.
